### ISSUE TITLE
Allow installation for use as default installer

### ISSUE THREAD

**Issue by HaleTom** [soupslurpr/AppVerifier#154]
To have apps be verified by default it would be great if AppVerifier could be set as the default installer.

I can't currently see a way to install an app through AppVerifier.

I suggest an "Install" button for streamlined workflow.

Eg, when I download an .APK file, I open it with AppVerifier, and then after seeing that it checks out, I want to install that APK.

### Current workflow
- tap apk file
- tap App Verifier (because it can't be set as default)
- tap verification (see verification source)
- hit back
- hit back (this time to exit AppVerifier
- open the apk again (may involve finding it if it was a completed download from notifications list)
- select app installer  (because it can't be set as default)
- tap Install

### Desired workflow
- tap apk file (opens in AppVerifier as it has been set as default app)
- tap verification to see  source (this step is actually optional if "install" is also listed on the main screen)
- tap "install"

**Comment by HaleTom** [comment]
It seems that the default installer is invoked when pressing "back" out of AppVerifier.  So my workflow is simple after all.

I will close this, but I'm curious:

Is there a way of selecting which installer is used?

**Comment by soupslurpr** [comment]
The default installer isn't invoked when going back, or at least not in every app. The apo you're using to open AppVerifier must be the one doing that.

**Comment by soupslurpr** [comment]
@HaleTom Unfortunately, this isn't a planned feature. I don't want AppVerifier to have an install option for two main reasons:

1. Extra code required to implement the installer.
2. It causes confusion as to the original source of the installed app and might mess with auto updates. If someone came from Obtainium and installed the app from AppVerifier, then I don't think Obtainium will be able to do auto updates for the app until the user does a manual update from Obtainium. I might be wrong on that though.
