### ISSUE TITLE
Four Enhancements

### ISSUE THREAD

**Issue by SyCoREAPER** [soupslurpr/AppVerifier#160]
1) Allow the manually verified apps to be added to the internal database so they can be marked verified. 

2) Allow importing and exporting of the internal database for phone restore/reinstalls, but only the signature, obviously not verification status. 

3) Ability to hide apps. I have language packs for example that don't get updated and clutter the list. 

4) Ability to sort apps either by name or package name.

**Comment by soupslurpr** [comment]
Please see my response #159 and make a single issue for each enhancement. Also the first enhancement is a duplicate or #153. Please search existing issues before creating a new one.

**Comment by SyCoREAPER** [comment]
Actually have a fifth, may require Shizuku or Root and probably fair amount of coding. 

"Verify All" button. Have it automatically go through and verify/flag apps.

**Comment by soupslurpr** [comment]
That's not possible though? How do you suggest it'd work?
