### ISSUE TITLE
armeabi-v7a support?

### ISSUE THREAD

**Issue by maxwell-thum** [soupslurpr/AppVerifier#161]
Phone: Cat S22 Flip
OS: Android 11 (Go edition)
Chipset: Qualcomm Snapdragon 425
ABI: armeabi-v7a

I get the following error when trying to install the APK from GitHub using ADB:
```
---@---:~/Downloads$ adb install AppVerifier-0.8.0.apk
Performing Streamed Install
adb: failed to install AppVerifier-0.8.0.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

```
I also tried installing from Accrescent and directly on my phone with no success.

**Comment by soupslurpr** [comment]
Unfortunately 32-bit devices aren't supported. I'd suggest getting a new device as you are on an outdated Android version that likely doesn't get security updates and can't make use of new privacy and security features in newer versions. The latest version of Android as of writing is 14, and 15 is almost here.
