### ISSUE TITLE
App status bug report

### ISSUE THREAD

**Issue by codeXXjs** [soupslurpr/AppVerifier#165]
Using the previous AppVerifier version 0.7.0 it shows Signal App as genuine. But after updating it to 0.8.0 it now shows Signal as unverified and not genuine. I tested the hash signature from the website and it is the same. 
Please see and address this issue. 
Thank you

**Comment by soupslurpr** [comment]
What device and Android version are you on? Could you send me a screenshot of Signal's screen in AppVerifier?
