### ISSUE TITLE
[Feature Request] Hash Displayed on Failure is Confusing: Hash Expected?  or Hash Found?

### ISSUE THREAD

**Issue by DiagonalArg** [soupslurpr/AppVerifier#180]
It's confusing to have the hash found, rather than the hash expected, presented on output when a check fails.  Going to check the key of the package reveals the hash to match, which leads to head scratching.  Perhaps you might output: Hash Expected and Hash Found?  Or even just "Expected: xx:xx:xx:xx"

**Comment by soupslurpr** [comment]
it's not. apps can have multiple versions that are signed with different keys but with the same variant so this wouldn't really work well anyways

**Comment by DiagonalArg** [comment]
Perhaps a list of those variants that were checked, in smaller type?  eg:

Found: xx:xx:xx...

Expected one of: 
yy:yy:yy
zz:zz:zz

**Comment by soupslurpr** [comment]
Okay, but what is this useful for?

**Comment by DiagonalArg** [comment]
> Okay, but what is this useful for?

First of all, it eliminates confusion.  When there's a failure (as in the image below) and that hash comes up, it's not clear if that's the hash of the package I just checked, or the hash that AppVerifier thinks I should have.

Second, if I know what hash AppVerifier may be expecting, I might be able to work out the issues; does AppVerifier have the wrong hash?  am I checking the wrong package?

![image](https://github.com/user-attachments/assets/8e4e8c35-deda-4ee0-ae1d-42558749fa50)

**Comment by soupslurpr** [comment]
on an unrelated note to this feature request, the entry in the database for the app in the screenshot you posted was outdated which is why verification was failing. I just updated the entry. I have clarified the CONTRIBUTING.md to indicate that notification of failing internal database entries is requested.
