### ISSUE TITLE
Why are no new app signatures allowed?

### ISSUE THREAD

**Issue by tegridyfarmer** [soupslurpr/AppVerifier#188]
I have seen https://github.com/soupslurpr/AppVerifier/blob/main/CONTRIBUTING.md but I could not find a reason.

**Comment by soupslurpr** [comment]
It's too time consuming

**Comment by grrrrr** [comment]
@soupslurpr for my own understanding, is the plan going forward that the end user will need to source the hashes and manually verify?   Or would there be some other way to get hashes into AppVerifier in bulk?

**Comment by soupslurpr** [comment]
The plan is to remove the internal database once Accrescent is open and has more apps. Users can always source the hashes and manually verify. It's easy to share verification info and it can be shared to AppVerifier as well to conveniently verify with others.

**Comment by soupslurpr** [comment]
Note that updates to existing entries will still be accepted as well as issues detailing which app has an outdated entry.
