### ISSUE TITLE
Signal verification failing

### ISSUE THREAD

**Issue by rxlecky** [soupslurpr/AppVerifier#189]
Signal app verification is currently failing on it's latest version (7.27.1) due to fingerpring mismatch. However there is a note in Signal's [release page](https://signal.org/android/apk/) saying:
> Note: Please update to the latest version of the [Android SDK Build Tools](https://developer.android.com/tools/releases/build-tools) for the best experience. If your apksigner command is out-of-date and doesn't support the latest Android APK Signature Scheme, you may see the following SHA-256 fingerprint for the 1024-bit signing certificate:
> 
> 29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0
EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26

This alternative fingerprint is actually matching. Does App Verifier need to update its Android SDK? Or does this need to be done locally on my device?

**Comment by soupslurpr** [comment]
Could you show me the hashes? What version of Signal?

**Comment by rxlecky** [comment]
Sorry, I mistakenly submitted empty report! 🙃 See updated comment above.

**Comment by soupslurpr** [comment]
What hashes show up for your Signal?

**Comment by soupslurpr** [comment]
Copy them and paste it here

**Comment by rxlecky** [comment]
The official hash: `4B:E4:F6:CD:5B:E8:44:08:3E:90:02:79:DC:82:2A:F6
5A:54:7F:EC:C2:6A:BA:7F:F1:F5:20:3A:45:51:8C:D8`
My hash: `29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0
EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26`

**Comment by rxlecky** [comment]
The one I'm getting matches the one that Signal's release page says will show up with outdated Android SDK (see the note at the bottom of the [release page](https://signal.org/android/apk/)).

**Comment by soupslurpr** [comment]
Hm... Where'd you get Signal from? Wait what's weird is the actual apk on the release page matches the one in AppVerifier's database. The one on their site is incorrect.

**Comment by rxlecky** [comment]
I got it from the official Signal release page. This is the concrete download link: https://updates.signal.org/android/Signal-Android-website-prod-universal-release-7.27.1.apk

**Comment by rxlecky** [comment]
Whoops, I copied the hashes with linebreak in the middle, sorry, my bad. Corrected the comment now. I checked the internal database, and it has both of the published hashes from their website. Could it be that it's only checking one of them for some reason?

**Comment by soupslurpr** [comment]
https://updates.signal.org/android/Signal-Android-website-prod-universal-release-7.27.1.apk
org.thoughtcrime.securesms
29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26
4B:E4:F6:CD:5B:E8:44:08:3E:90:02:79:DC:82:2A:F6:5A:54:7F:EC:C2:6A:BA:7F:F1:F5:20:3A:45:51:8C:D8

While mine is
org.thoughtcrime.securesms
29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26
4B:E4:F6:CD:5B:E8:44:08:3E:90:02:79:DC:82:2A:F6:5A:54:7F:EC:C2:6A:BA:7F:F1:F5:20:3A:45:51:8C:D8

The site says
4B:E4:F6:CD:5B:E8:44:08:3E:90:02:79:DC:82:2A:F6:5A:54:7F:EC:C2:6A:BA:7F:F1:F5:20:3A:45:51:8C:D8

**Comment by soupslurpr** [comment]
Everything's correct. The first hash is the old one and the second one is the new one. It verifies correctly in AppVerifier. Can you press Share/Copy Verification Info in AppVerifier and paste exactly that here? Thanks.

**Comment by rxlecky** [comment]
Sure thing, here it is:
org.thoughtcrime.securesms
29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26

Unlike yours, mine only has one hash, is that the issue?

Also, the site actually lists both hashes. The second one is listed in a little callout box at the bottom of the page.

**Comment by soupslurpr** [comment]
That's not good. It was supposed to be rotated to another key because the old one was only 1024-bit so it was becoming insecure.

**Comment by soupslurpr** [comment]
Hmm it should be rotated

**Comment by soupslurpr** [comment]
What device and OS are you using?

**Comment by rxlecky** [comment]
I'm on Android 12, the device is Samsung Galaxy A41.

**Comment by soupslurpr** [comment]
It might not rotate on Android 12. Could you download the apk and open the apk itself in AppVerifier and send its verification info?

**Comment by rxlecky** [comment]
The info I sent above was from the apk directly. I downloaded apk, and selected `Verify APK file`, instead of going through the app list.

**Comment by soupslurpr** [comment]
Then I'm stumped. I wouldn't be surprised if it's because of the phone. I've seen a lot of issues with Samsung A-series phones. I highly recommend getting one of these phones and installing GrapheneOS onto them if you care about privacy and security: https://grapheneos.org/faq#recommended-devices

**Comment by rxlecky** [comment]
Thanks for the recommendation! 🙂 Graphene is on my radar, and a custom ROM is something I want to move to eventually but I will have to wait before investing into a new device.

I guess the issue can be closed if it's device specific?

**Comment by soupslurpr** [comment]
@ThreeDeeJay could you send a screenshot?

**Comment by ThreeDeeJay** [comment]
@soupslurpr Same whether I search for Signal in the app list or open the [APK](https://updates.signal.org/android/Signal-Android-website-prod-universal-release-7.45.3.apk) directly with AppVerifier (force closed and cleared data to make sure the check isn't outdated)

![Image](https://github.com/user-attachments/assets/ef528bd7-acdd-4cff-b284-074c8c01ac0f)

**Comment by Fak3** [comment]
Same issue here, on Android 12 MIUI 13.0.9 POCO X3 Pro phone, please reopen.
