### ISSUE TITLE
Overload

### ISSUE THREAD

**Issue by pabloscloud** [soupslurpr/AppVerifier#19]
# Package name
cloud.pablos.overload

# Hash(es)
4D:1D:43:17:A6:F5:7B:95:89:90:D2:39:1D:07:52:4E:D1:D5:4D:D3:4C:35:01:A1:B4:02:13:36:66:AE:A3:B3

**Comment by soupslurpr** [comment]
I can't seem to find the apk / place of getting the app where the hash is `4D:1D:43:17:A6:F5:7B:95:89:90:D2:39:1D:07:52:4E:D1:D5:4D:D3:4C:35:01:A1:B4:02:13:36:66:AE:A3:B3`, I only see `BD:39:CA:B0:CB:22:4D:4A:E0:97:95:11:F3:24:1E:D8:85:8D:1A:F8:69:37:B7:C6:39:7B:E4:BA:7E:C1:A2:B4` for Codeberg, Google Play Store, and F-Droid.

**Comment by pabloscloud** [comment]
Add that then 😅 It tells me the wrong hash for some reason lol.

`BD:39:CA:B0:CB:22:4D:4A:E0:97:95:11:F3:24:1E:D8:85:8D:1A:F8:69:37:B7:C6:39:7B:E4:BA:7E:C1:A2:B4` is correct as stated in the last release.

**Comment by pabloscloud** [comment]
> For you it shows the one starting with 4D?

It did. I guess it could be because that's the version that I compiled and debugged on my phone.

But when I installed the apk it showed the "correct" one starting with BD

**Comment by soupslurpr** [comment]
Ah you gotta remember debug apps are supposed to be signed with a debug signing key so that's why it was the one starting with 4D

**Comment by soupslurpr** [comment]
I'll add Overload to the internal verification info database soon

**Comment by soupslurpr** [comment]
Most apps are on the play store, so I just search there. Apps that have a GitHub usually say where to download it on stores, but if they don't I search F-Droid too.

**Comment by pabloscloud** [comment]
Maybe it would make sense to let users add a link to the GitHub issue just so it's very clear, but if that search isn't too big of a problem for you I don't mind either.

**Comment by soupslurpr** [comment]
There, added.



> Maybe it would make sense to let users add a link to the GitHub issue just so it's very clear, but if that search isn't too big of a problem for you I don't mind either.

Sure, thanks for the suggestion. I'll add an optional field for that

**Comment by pabloscloud** [comment]
Thanks :)
