### ISSUE TITLE
Supply APK file for verification

### ISSUE THREAD

**Issue by matchboxbananasynergy** [soupslurpr/AppVerifier#2]
The way AppVerifier currently works, an app has to first be installed before the app can find it and verify it.

Ideally, AppVerifier should be able to accept an APK file and allow the user to verify it before needing to install it.

**Comment by life00** [comment]
Might be useful to hook up an Installer prompt right away if verification is successful. If https://github.com/soupslurpr/AppVerifier/issues/5 is implemented it might be especially nice to first pass the APK through AppVerifier and if successful prompt to install (obviously its better to implement this at OS level, but :shrug:).

**Comment by life00** [comment]
Could be an optional setting?

**Comment by soupslurpr** [comment]
I don't think it should install the app either.

**Comment by soupslurpr** [comment]
It seems https://android.googlesource.com/platform/tools/apksig/ should be able to be used for parsing the APK file.

**Comment by soupslurpr** [comment]
Hmm but then what to use for getting the package name?

**Comment by soupslurpr** [comment]
Right, we can parse the manifest manually I think

**Comment by lberrymage** [comment]
> It seems https://android.googlesource.com/platform/tools/apksig/ should be able to be used for parsing the APK file to get the SHA-256 hash of the signing certificate.
> 
> `com.android.tools.build:apksig`

apksig would work, but there's actually an OS API for this: https://developer.android.com/reference/android/content/pm/PackageManager#getPackageArchiveInfo(java.lang.String,%20android.content.pm.PackageManager.PackageInfoFlags).

**Comment by soupslurpr** [comment]
Hmm but that won't be able to be used with SAF

**Comment by soupslurpr** [comment]
Oh wait never mind can just copy the file to cache directory temporarily
