### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by w9925** [soupslurpr/AppVerifier#23]
# Package name
com.google.android.youtube
# Hash(es)

3D:7A:12:23:01:9A:A3:9D:9E:A0:E3:43:6A:B7:C0:89:6B:FB:4F:B6:79:F4:DE:5F:E7:C2:3F:32:6C:8F:99:4A

**Comment by soupslurpr** [comment]
Please wait for the next version for now. The next version will change the way the verification info is shared and parsed as it will add support for multiple signers and key rotation
