### ISSUE TITLE
Move the hashes of internal database to GitHub

### ISSUE THREAD

**Issue by w9925** [soupslurpr/AppVerifier#25]
It seems more practical to avoid storing the hashes statically in the app and instead outsource them to a file on GitHub. This file could be synchronized at regular intervals. This approach allows for the hashes to be updated without the need to release a new app update each time.

**Comment by soupslurpr** [comment]
I'd like to keep the app offline, and also it complicates the app to implement that. I don't think it is a major issue.

**Comment by soupslurpr** [comment]
But of course I could be wrong and it will become an issue in the future, it will be considered in that case
