### ISSUE TITLE
LocalSend

### ISSUE THREAD

**Issue by greensheeps** [soupslurpr/AppVerifier#27]
# Package name
org.localsend.localsend_app
# Hash(es)
Google Play Store
BB:3E:E2:82:39:B1:41:8A:F1:6D:DC:64:7D:5A:94:8A:57:3C:2D:13:6D:2B:74:BC:E4:7E:9D:8E:23:35:30:4E
F-Droid/GitHub
32:20:C3:53:A7:3C:FB:D0:C2:F3:05:24:71:C4:45:32:4C:F4:52:BC:BA:26:DE:1C:47:3A:52:FE:5C:44:E1:D6

**Comment by soupslurpr** [comment]
completed in https://github.com/soupslurpr/AppVerifier/commit/b6e9663be63d08915246ab1431f77068db1edb75
