### ISSUE TITLE
KeePassDX

### ISSUE THREAD

**Issue by greensheeps** [soupslurpr/AppVerifier#29]
# Package name
com.kunzisoft.keepass.free
# Hash(es)
Google Play Store
46:D5:15:D5:F4:15:72:42:0C:EF:30:C0:7B:52:6B:F2:C4:0F:C4:A1:13:EF:19:1F:4F:9D:F9:01:2E:09:1F:35
GitHub
7D:55:B8:AF:21:03:81:AA:BF:96:0F:07:E1:7C:F7:85:7B:6D:2A:64:2C:A2:DA:6B:F0:BD:F1:B2:00:36:2F:04

**Comment by life00** [comment]
already working on it on my PR. I will add these hashes.
