### ISSUE TITLE
KeePassDX (libre)

### ISSUE THREAD

**Issue by greensheeps** [soupslurpr/AppVerifier#30]
# Package name
com.kunzisoft.keepass.libre
# Hash(es)
GitHub
7D:55:B8:AF:21:03:81:AA:BF:96:0F:07:E1:7C:F7:85:7B:6D:2A:64:2C:A2:DA:6B:F0:BD:F1:B2:00:36:2F:04
F-Droid
C8:10:AA:B7:EF:A4:D5:AD:3F:C2:94:1F:DF:5F:99:B8:8A:3B:73:F8:62:19:71:56:27:ED:B4:DA:BA:C5:41:A4

**Comment by soupslurpr** [comment]
C

**Comment by soupslurpr** [comment]
Check matrix

**Comment by life00** [comment]
I will add this to my PR too
