### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by w9925** [soupslurpr/AppVerifier#33]
# Package name
org.fossify.calendar

# Hash(es)

AF:FD:B1:24:D3:F4:72:0C:2F:98:DB:CA:9E:AC:BA:05:14:FB:A4:30:6E:20:A2:78:6C:86:1C:3C:0D:6F:F2:92

# Source code link (Optional)
https://github.com/FossifyOrg/Calendar

**Comment by life00** [comment]
would be nice to add all Fossify apps. planning to do that unless you make a PR before that.

**Comment by life00** [comment]
ok wait actually do not add this or any Fossify apps. This is a newly forked project and they still figure out the name and app sources. Please wait for a month and check their status again.

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
