### ISSUE TITLE
Element X

### ISSUE THREAD

**Issue by w9925** [soupslurpr/AppVerifier#34]
# Package name
io.element.android.x
# Hash(es)

C6:DB:9B:9C:8C:BD:D6:5D:16:E8:EC:8C:8B:91:C8:31:B9:EF:C9:5C:BF:98:AE:41:F6:A9:D8:35:15:1A:7E:16
# Source code link (Optional)
https://github.com/vector-im/element-x-android

**Comment by life00** [comment]
already in my PR

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
