### ISSUE TITLE
Pixel Camera Services

### ISSUE THREAD

**Issue by w9925** [soupslurpr/AppVerifier#35]
# Package name
com.google.android.apps.camera.services
# Hash(es)

22:6B:B0:43:9D:6B:AE:AA:5A:39:7C:58:6E:70:31:D8:AD:DF:AE:C7:3C:65:BE:21:2F:4A:5D:BF:BF:62:1B:92
# Source code link (Optional)

https://play.google.com/store/apps/details?id=com.google.android.apps.camera.services

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
