### ISSUE TITLE
Wireguard

### ISSUE THREAD

**Issue by w9925** [soupslurpr/AppVerifier#36]
# Package name
com.wireguard.android
# Hash(es)
IzzyOnDroid
84:A1:3F:A2:C4:E0:06:4B:0C:11:65:4B:8A:86:57:4B:7A:9B:93:52:A3:83:4C:EE:32:45:5B:06:1C:3D:41:27
# Source code link (Optional)

**Comment by life00** [comment]
Can't find F-Droid wireguard version. This hash is for official website and play store APKs

**Comment by soupslurpr** [comment]
IzzyOnDroid is different than F-Droid

**Comment by soupslurpr** [comment]
So I'd edit it to say IzzyOnDroid

**Comment by zx2c4** [comment]
https://lists.zx2c4.com/pipermail/wireguard/2023-April/008045.html

Everything uses the same key. `84a13fa2c4e0064b0c11654b8a86574b7a9b9352a3834cee32455b061c3d4127` is the only key that should be listed anywhere.

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
