### ISSUE TITLE
WG Tunnel

### ISSUE THREAD

**Issue by w9925** [soupslurpr/AppVerifier#39]
# Package name
com.zaneschepke.wireguardautotunnel
# Hash(es)
F-droid
69:49:37:7F:86:39:D0:3E:90:AF:27:94:26:40:97:34:31:99:8F:CF:34:1E:0B:BE:87:0F:76:40:C8:7F:24:4D

Github
52:04:D8:2E:76:6E:8A:A1:4D:CB:B0:6D:C7:0A:EB:AE:2B:DD:81:2D:4D:62:03:CD:52:1A:8A:68:5D:7D:3D:80
# Source code link (Optional)
https://github.com/zaneschepke/wgtunnel

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
