### ISSUE TITLE
Cromite

### ISSUE THREAD

**Issue by Penknife0915** [soupslurpr/AppVerifier#51]
# Package name
org.cromite.cromite

# Hash(es)
63:3F:A4:1D:82:11:D6:D0:91:6A:81:9B:89:66:8C:6D:E9:2E:64:23:2D:A6:7F:9D:16:FD:81:C3:B7:E9:23:FF

# Source code link (Optional)
https://github.com/uazo/cromite

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
