### ISSUE TITLE
FTPClient

### ISSUE THREAD

**Issue by Penknife0915** [soupslurpr/AppVerifier#52]
# Package name
de.qwerty287.ftpclient

# Hash(es)
EB:CD:A4:06:40:F9:99:76:23:C5:54:A7:B9:8D:5A:53:1E:62:5A:A1:35:DE:BB:CC:65:8A:CA:11:D6:7F:D5:82

# Source code link (Optional)
https://codeberg.org/qwerty287/ftpclient

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
