### ISSUE TITLE
Locus

### ISSUE THREAD

**Issue by Penknife0915** [soupslurpr/AppVerifier#53]
# Package name
app.myzel394.locus

# Hash(es)
85:E4:B5:DB:23:82:B2:B0:AC:F0:C2:C6:B2:F6:71:D6:DF:57:DA:42:86:BD:56:CB:D0:4F:8C:5B:29:62:65:54

# Source code link (Optional)
https://github.com/Myzel394/locus

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
