### ISSUE TITLE
Megacubo

### ISSUE THREAD

**Issue by Penknife0915** [soupslurpr/AppVerifier#54]
# Package name
tv.megacubo.app

# Hash(es)
A4:77:EA:2E:F0:40:F1:ED:B5:8B:21:BD:EE:91:5A:41:C3:3F:62:CE:BA:D6:23:9C:48:5A:C3:11:30:1C:3D:73

# Source code link (Optional)
https://github.com/EdenwareApps/Megacubo

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
