### ISSUE TITLE
You Have Mail

### ISSUE THREAD

**Issue by Penknife0915** [soupslurpr/AppVerifier#55]
# Package name
dev.lbeernaert.youhavemail

# Hash(es)
1B:B4:B3:43:AA:70:5F:49:B7:3B:3E:F4:89:C9:87:DD:2E:2F:68:4C:C1:B6:EB:49:F6:25:BC:BF:6C:8F:01:EE

# Source code link (Optional)
https://github.com/LeanderBB/you-have-mail

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
