### ISSUE TITLE
Cloudstream

### ISSUE THREAD

**Issue by Penknife0915** [soupslurpr/AppVerifier#56]
# Package name
com.lagradost.cloudstream3

# Hash(es)
9B:4F:6C:87:EE:B7:0B:25:7C:7F:96:8E:65:B1:56:16:82:4B:CE:33:E9:CC:74:A0:7A:D3:DD:26:63:2A:1D:B7

# Source code link (Optional)
https://github.com/recloudstream/cloudstream

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
