### ISSUE TITLE
Cryptomator

### ISSUE THREAD

**Issue by Penknife0915** [soupslurpr/AppVerifier#57]
# Package name
org.cryptomator

# Hash(es)
F7:C3:EC:3B:0D:58:8D:3C:B5:29:83:E9:EB:1A:74:21:C9:3D:43:39:A2:86:39:8E:71:D7:B6:51:E8:D8:EC:DD

# Source code link (Optional)
https://github.com/cryptomator/android

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
