### ISSUE TITLE
Seal

### ISSUE THREAD

**Issue by Penknife0915** [soupslurpr/AppVerifier#58]
# Package name
com.junkfood.seal

# Hash(es)
44:93:58:2A:41:48:DF:38:FC:26:90:73:C8:78:7C:31:C4:31:ED:5B:6D:62:71:08:92:A0:40:6F:F5:0C:4D:67

# Source code link (Optional)
https://github.com/JunkFood02/Seal

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
