### ISSUE TITLE
Ability to export all app ID's and signature hashes

### ISSUE THREAD

**Issue by life00** [soupslurpr/AppVerifier#6]
I suggest to implement a feature allowing to easily export all app ID's and corresponding signature hashes in some reasonable format. Would be very useful when compiling a list of app ID's + hashes.  

Especially useful if https://github.com/soupslurpr/AppVerifier/issues/5 is implemented: makes the contributions to the database extremely easy. I would recommend making an option to export in the same format as the database format.

**Comment by life00** [comment]
additional functionality to export only selected app ID's + hashes.

**Comment by soupslurpr** [comment]
I don't see a point in this, #7 seems better
