### ISSUE TITLE
Squawker

### ISSUE THREAD

**Issue by Penknife0915** [soupslurpr/AppVerifier#60]
# Package name
org.ca.squawker

# Hash(es)
39:FB:AE:AF:F1:D5:C7:76:73:8F:28:01:EF:26:02:F6:30:5C:7D:8A:C4:D2:F1:E3:9E:E6:E2:36:89:39:95:E3

# Source code link (Optional)
https://github.com/j-fbriere/squawker

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
