### ISSUE TITLE
Nextcloud

### ISSUE THREAD

**Issue by rusty-snake** [soupslurpr/AppVerifier#68]
# Package name

com.nextcloud.client

# Hash(es)

FB:00:95:22:F6:5E:25:80:22:61:B6:7B:10:A4:5F:D7:0E:61:00:31:97:6F:40:B2:8A:64:9E:15:2D:ED:03:73

# Source code link (Optional)

https://github.com/nextcloud/android

(Non-gplay release)

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
