### ISSUE TITLE
aves

### ISSUE THREAD

**Issue by rusty-snake** [soupslurpr/AppVerifier#69]
# Package name

deckers.thibault.aves

# Hash(es)

F4:79:47:27:E4:54:16:D8:7C:48:71:38:29:2B:70:9F:11:D1:CD:7D:AB:55:84:D8:C6:85:7D:92:E0:66:60:4B

# Source code link (Optional)

https://github.com/deckerst/aves

(Accrescent)

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
