### ISSUE TITLE
Just (Video) Player

### ISSUE THREAD

**Issue by rusty-snake** [soupslurpr/AppVerifier#70]
# Package name

Just (Video) Player

# Hash(es)

3C:B9:7D:BA:57:D3:D0:BC:19:0B:AE:5F:1F:3A:84:16:43:BC:D9:39:9B:C3:10:28:CE:25:77:5D:93:D0:10:9D

# Source code link (Optional)

https://github.com/moneytoo/Player

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
