### ISSUE TITLE
Noto

### ISSUE THREAD

**Issue by rusty-snake** [soupslurpr/AppVerifier#71]
# Package name
com.noto
# Hash(es)
DF:E4:DF:B2:D0:6E:DB:86:BF:93:C2:43:93:55:E9:E2:43:EF:3C:08:5E:02:C4:EC:C6:FA:86:FF:30:95:FD:5E

# Source code link (Optional)

https://github.com/alialbaali/Noto

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
