### ISSUE TITLE
QRServ

### ISSUE THREAD

**Issue by rusty-snake** [soupslurpr/AppVerifier#72]
# Package name
dev.uint.qrserv
# Hash(es)
DF:B4:DA:EE:79:FF:F9:95:B8:F8:75:29:5E:01:CF:E3:B3:9C:11:1E:D9:03:DE:E0:13:A5:A9:CA:AD:2B:BA:65

# Source code link (Optional)

https://github.com/uintdev/qrserv

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
