### ISSUE TITLE
Zapp

### ISSUE THREAD

**Issue by rusty-snake** [soupslurpr/AppVerifier#73]
# Package name
de.christinecoenen.code.zapp

# Hash(es)
A7:5D:6D:3B:1F:96:22:0B:F0:60:8A:E7:57:D4:15:AE:60:CC:2B:64:DE:4A:45:C4:5C:BD:BE:1F:92:A1:27:A0

# Source code link (Optional)

https://github.com/mediathekview/zapp

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
