### ISSUE TITLE
FlashDim

### ISSUE THREAD

**Issue by rusty-snake** [soupslurpr/AppVerifier#74]
# Package name
com.cyb3rko.flashdim
# Hash(es)
EA:78:69:1C:BA:41:86:00:A4:56:32:89:B1:33:F9:D0:0D:3D:0C:24:A5:F5:4C:5C:59:EE:1C:95:2B:B0:E1:1D

# Source code link (Optional)

https://github.com/cyb3rko/flashdim

**Comment by soupslurpr** [comment]
As of now, contributing through issues won't be accepted. Please check the updated https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for instructions. Thanks.
